### ISSUE TITLE
1.1.0 version has SyntaxError in build script. Does not show customization screen.

### ISSUE THREAD

**Issue by Davenport-Physics** [snakewiz/fivem-appearance#2]
![image](https://user-images.githubusercontent.com/1410579/112649025-1190e580-8e18-11eb-99cd-987724379ead.png)

Customization screen does not show up in the left.

![image](https://user-images.githubusercontent.com/1410579/112649088-1f466b00-8e18-11eb-8373-a30b844970a3.png)

in my server.cfg
```
setr fivem-appearance:customization 1
ensure fivem-appearance
```

The code I'm using to call this

```lua
function open_clothing_store()

    local config = {
        ped = false,
        headBlend = false,
        faceFeatures = false,
        headOverlays = false,
        components = true,
        props = true
    }

    TriggerEvent("cd_drawtextui:temp_hide_text")
    exports['fivem-appearance']:startPlayerCustomization(function(appearance)

        if appearance then
            exports["em_fw"]:update_skin(json.encode(appearance))
            TriggerEvent("cui_wardrobe:open")
        end
        TriggerEvent("cd_drawtextui:temp_show_text")
        
    end, config)

end
```

**Comment by Davenport-Physics** [comment]
I have no issue with the 1.0 build, but of course, that one is missing config.

**Comment by snakewiz** [comment]
I had no success trying to reproduce your issue on my end. Looks like it's something related to parsing the locales file? Try to add this line into your config, before ensuring the resource.
```bash
setr fivem-appearance:locale "en"
```

**Comment by Davenport-Physics** [comment]
Alright. I had that line before, it didn't quite make a difference on my end.

Adding that line once more, doesn't clear up the syntax issue nor the issue with the interface being gone.

```
setr fivem-appearance:customization 1
setr fivem-appearance:locale "en"
ensure fivem-appearance
```

Not sure what's going on.

**Comment by Davenport-Physics** [comment]
I've cleared server and client cache, which didn't help. I've switched the fivem build from stable to canary, no dice there.

Exports are working fine, just no interface. I've had other clients report the same issue.
